apiVersion: apps/v1
kind: Deployment
metadata:
  name: drumstick-web
  namespace: cluckn-bell-dev
  labels:
    app: drumstick-web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: drumstick-web
  template:
    metadata:
      labels:
        app: drumstick-web
    spec:
      serviceAccountName: drumstick-web
      containers:
        - name: web
          image: 264765154707.dkr.ecr.us-east-1.amazonaws.com/cluckin-bell-app:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_SITE_URL
              value: "https://dev.cluckn-bell.com"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: runtime-config
              mountPath: /usr/share/nginx/html/env.js
              subPath: env.js
      volumes:
        - name: runtime-config
          configMap:
            name: drumstick-web-runtime-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wingman-api
  namespace: cluckn-bell-dev
  labels:
    app: wingman-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wingman-api
  template:
    metadata:
      labels:
        app: wingman-api
    spec:
      serviceAccountName: wingman-api
      containers:
        - name: api
          image: 264765154707.dkr.ecr.us-east-1.amazonaws.com/wingman-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ROOT_PATH
              value: "/api"
            - name: CMS_BASE_URL
              value: "http://cms-svc."
            - name: WORDPRESS_SITE_URL
              value: "https://dev.cluckn-bell.com"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3