apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.alertmanager: |
    url: $webhook-url
    headers:
      - name: Content-Type
        value: application/json
  template.app-deployed: |
    message: |
      :white_check_mark: Application {{.app.metadata.name}} is now running new version in {{.app.spec.destination.namespace}}.
  template.app-health-degraded: |
    message: |
      :exclamation: Application {{.app.metadata.name}} has degraded in {{.app.spec.destination.namespace}}.
  template.app-sync-failed: |
    message: |
      :x: Application {{.app.metadata.name}} sync failed.
  trigger.on-deployed: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      send: [app-deployed]
  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-health-degraded]
  trigger.on-sync-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed]
