apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../platform/argocd/apps
- cluster-secret-store.yaml

patchesStrategicMerge:
- external-dns-values.yaml
- cluster-autoscaler-values.yaml
- kube-prometheus-stack-values.yaml
- aws-for-fluent-bit-values.yaml