apiVersion: v2
name: app-wingman-api
description: Helm chart for Cluckin Bell wingman API application

type: application

# This is the chart version
version: 0.1.0

# This is the version number of the application being deployed
appVersion: "1.0.0"
