apiVersion: v2
name: app-frontend
description: Helm chart for Cluckin Bell frontend application (drumstick-web)

type: application

# This is the chart version
version: 0.1.0

# This is the version number of the application being deployed
appVersion: "1.0.0"
