apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::264765154707:role/cb-external-secrets-role
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: wordpress-secret
    creationPolicy: Owner
  data:
  - secretKey: wordpress-password
    remoteRef:
      key: cluckin-bell/dev/wordpress/admin
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mariadb-secret
    creationPolicy: Owner
  data:
  - secretKey: mariadb-root-password
    remoteRef:
      key: cluckin-bell/dev/mariadb/root
      property: password
  - secretKey: mariadb-password
    remoteRef:
      key: cluckin-bell/dev/mariadb/user
      property: password