apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: cluckn-bell-platform
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.9.6
    chart: argocd-image-updater
    helm:
      values: |
        config:
          registries:
            - name: ECR
              api_url: https://264765154707.dkr.ecr.us-east-1.amazonaws.com
              prefix: 264765154707.dkr.ecr.us-east-1.amazonaws.com
              credentials: ext:/scripts/ecr-login.sh
              credsexpire: 10h
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
