apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: cluckn-bell-platform
  source:
    repoURL: https://github.com/oscarmartinez0880/cluckin-bell
    targetRevision: HEAD
    path: charts/karpenter
    helm:
      valueFiles:
        - ../../values/platform/karpenter-nonprod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
