---
name: Deploy Manifests

'on':
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev|qa|prod)"
        required: true
        default: "dev"
        type: choice
        options: [dev, qa, prod]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN_EKS }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region "${{ vars.AWS_REGION }}" \
            --name "${{ vars.EKS_CLUSTER_NAME }}"

      - name: Apply manifests
        run: |
          ENV="${{ github.event.inputs.environment }}"
          echo "Deploying to environment: ${ENV}"
          echo "Target namespace: cluckin-bell-${ENV}"
          kubectl apply -f k8s/${ENV}/

      - name: Verify deployment
        run: |
          ENV="${{ github.event.inputs.environment }}"
          NAMESPACE="cluckin-bell-${ENV}"

          # Use KUBE_NAMESPACE if available, otherwise use the
          # environment-based namespace
          if [ -n "${{ vars.KUBE_NAMESPACE }}" ]; then
            NAMESPACE="${{ vars.KUBE_NAMESPACE }}"
            echo "Using KUBE_NAMESPACE: ${NAMESPACE}"
          else
            echo "Using default namespace: ${NAMESPACE}"
          fi

          echo "Checking deployment status in namespace: ${NAMESPACE}"
          kubectl get all -n ${NAMESPACE}
          kubectl get configmap -n ${NAMESPACE}
          kubectl get serviceaccount -n ${NAMESPACE}
